name: Release
on:
  release:
    types:
      - published
  workflow_dispatch: null

jobs:
  publish:
    name: publish-on-pypi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock
      - name: Install the project
        run: uv sync
      - name: Build the project
        run: uv build
      - name: Publish the project
        run: uv publish # ensure that UV_PUBLISH_TOKEN env variable is set
